version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tender
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - "3369:3306"

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=admin:123@tcp(db:3306)/tender?parseTime=true
