name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tender
          MYSQL_USER: admin
          MYSQL_PASSWORD: 123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Install dependencies
      run: go mod download

    - name: Build the project
      run: go build -o /app/tender ./cmd/tender

    - name: Run tests
      env:
        DATABASE_URL: admin:123@tcp(127.0.0.1:3306)/tender?parseTime=true
      run: go test ./...

    - name: Build Docker image
      run: docker build -t my-go-app .

    - name: Push Docker image
      run: echo "Docker push step - to be configured"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: echo "Deployment step - to be configured"
